import { v } from "convex/values";
import { action, mutation } from "./_generated/server";
export const saveAudit = mutation({ args:{company_id:v.optional(v.string()),lead_id:v.optional(v.string()),audit_type:v.string(),result:v.any(),source_data:v.any()}, handler:async(ctx,args)=>{const identity=await ctx.auth.getUserIdentity();if(!identity)throw new Error("Not authenticated");const workspace=await ctx.db.query("workspaces").withIndex("by_owner",(q:any)=>q.eq("ownerSubject",identity.subject)).unique();if(!workspace)throw new Error("Workspace missing");const r=args.result??{};const id=await ctx.db.insert("ai_audits",{workspace_id:workspace._id.toString(),company_id:args.company_id,lead_id:args.lead_id,audit_type:args.audit_type,overall_score:typeof r.overall_score==="number"?r.overall_score:undefined,strengths:Array.isArray(r.strengths)?r.strengths.map(String):[],weaknesses:Array.isArray(r.weaknesses)?r.weaknesses.map(String):[],opportunities:Array.isArray(r.opportunities)?r.opportunities.map(String):[],recommended_actions:Array.isArray(r.recommended_actions)?r.recommended_actions.map(String):[],priority:typeof r.priority==="string"?r.priority:undefined,source_data:args.source_data,created_at:new Date().toISOString()});return id.toString();}});
function s(x:any){return typeof x==="string"?x.trim():""}
function qualify(lead:any){const b=JSON.stringify(lead??{}).toLowerCase();let score=0;if(s(lead?.company??lead?.company_name))score+=25;if(/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(s(lead?.email)))score+=20;if(s(lead?.website??lead?.company_website))score+=15;if(s(lead?.phone))score+=5;if(/usa|united states|saudi|uae|qatar|bahrain|dubai|riyadh|jeddah|doha|manama/.test(b))score+=15;if(/social media|marketing|instagram|facebook|content|lead generation|growth|agency/.test(b))score+=10;if(/roofing|egypt/.test(b))score-=30;score=Math.max(0,Math.min(100,score));const qualification=score>=70?"high":score>=45?"medium":"low";return{score,qualification,reasoning:"Deterministic evidence-based qualification fallback; no external model credential is configured.",recommended_action:qualification==="high"?"Review evidence and prepare a tailored outreach draft; do not send automatically.":qualification==="medium"?"Collect missing business evidence before drafting outreach.":"Do not outreach; enrich or reject the lead.",confidence:.55,method:"rule_based_fallback"}}
function audit(input:any){const b=JSON.stringify(input??{}).toLowerCase();const strengths:string[]=[],weaknesses:string[]=[],opportunities:string[]=[];if(/facebook|instagram|social/.test(b))strengths.push("Social context is present in supplied evidence.");if(/website|url/.test(b))strengths.push("Web presence is referenced in supplied evidence.");if(!/website|url/.test(b))weaknesses.push("No website evidence was supplied.");if(!/email/.test(b))weaknesses.push("No email evidence was supplied.");if(/marketing|content|lead|growth/.test(b))opportunities.push("Use the stated growth context to form a service hypothesis.");opportunities.push("Collect verifiable public evidence before outreach.");const score=Math.max(0,Math.min(100,50+strengths.length*12+opportunities.length*5-weaknesses.length*10));return{overall_score:score,strengths,weaknesses,opportunities,recommended_actions:["Verify source evidence","Draft only; human approval remains required before sending"],priority:score>=70?"high":score>=45?"medium":"low",method:"rule_based_fallback"}}
async function model(prompt:string){const key=process.env.GEMINI_API_KEY;if(!key)return null;try{const r=await fetch("https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent",{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":key},body:JSON.stringify({contents:[{role:"user",parts:[{text:prompt}]}],generationConfig:{responseMimeType:"application/json"}})});if(!r.ok)return null;const d=await r.json();const t=d?.candidates?.[0]?.content?.parts?.[0]?.text;return t?JSON.parse(t):null}catch{return null}}
export const growthAudit=action({args:{input:v.any()},handler:async(_ctx,args)=>(await model("Return strict JSON for a marketing growth audit with fields overall_score, strengths, weaknesses, opportunities, recommended_actions, priority. Input: "+JSON.stringify(args.input)))??audit(args.input)});
export const qualifyLead=action({args:{lead:v.any()},handler:async(_ctx,args)=>(await model("Return strict JSON for lead qualification with fields score, qualification, reasoning, recommended_action, confidence. Input: "+JSON.stringify(args.lead)))??qualify(args.lead)});
