import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";
const json = v.any();
export default defineSchema({
  workspaces: defineTable({ name: v.string(), ownerSubject: v.string(), created_at: v.string() }).index("by_owner", ["ownerSubject"]),
  companies: defineTable({ workspace_id: v.string(), name: v.string(), domain: v.optional(v.string()), industry: v.string(), size_category: v.optional(v.string()), estimated_annual_revenue: v.optional(v.number()), country: v.string(), created_at: v.string(), updated_at: v.string() }).index("by_workspace", ["workspace_id"]),
  contacts: defineTable({ workspace_id: v.string(), company_id: v.string(), full_name: v.string(), email: v.string(), phone: v.string(), job_title: v.string(), is_decision_maker: v.boolean(), linkedin_url: v.optional(v.string()), created_at: v.string() }).index("by_workspace", ["workspace_id"]).index("by_company", ["company_id"]),
  leads: defineTable({ workspace_id: v.string(), company_id: v.string(), contact_id: v.string(), idempotency_key: v.optional(v.string()), contact_name: v.string(), company_name: v.string(), avatar_url: v.optional(v.string()), email: v.string(), phone: v.string(), source: v.string(), industry: v.string(), monthly_budget: v.number(), estimated_value: v.number(), stage: v.string(), status: v.string(), last_activity: v.string(), notes: v.optional(v.string()), assigned_agent: v.string(), next_follow_up_at: v.optional(v.string()), automation_status: v.string(), likes_count: v.number(), liked_by_me: v.boolean(), created_at: v.string(), updated_at: v.string(), ai_score: v.optional(v.number()), ai_qualification: v.optional(v.string()), ai_reasoning: v.optional(v.string()), ai_recommended_action: v.optional(v.string()), ai_confidence: v.optional(v.number()), ai_evaluated_at: v.optional(v.string()) }).index("by_workspace", ["workspace_id"]).index("by_idempotency", ["idempotency_key"]),
  campaigns: defineTable({ workspace_id: v.string(), company_id: v.optional(v.string()), page_id: v.optional(v.string()), name: v.string(), objective: v.string(), status: v.string(), budget: v.number(), leads_count: v.number(), spend: v.number(), starts_at: v.optional(v.string()), ends_at: v.optional(v.string()), created_at: v.string() }).index("by_workspace", ["workspace_id"]),
  conversations: defineTable({ workspace_id: v.string(), lead_id: v.string(), page_id: v.optional(v.string()), channel: v.string(), status: v.string(), last_message_at: v.string(), created_at: v.string() }).index("by_workspace", ["workspace_id"]).index("by_lead", ["lead_id"]),
  messages: defineTable({ workspace_id: v.string(), conversation_id: v.string(), direction: v.string(), sender_name: v.string(), body: v.string(), ai_generated: v.boolean(), created_at: v.string() }).index("by_conversation", ["conversation_id"]).index("by_workspace", ["workspace_id"]),
  audit_logs: defineTable({ workspace_id: v.string(), action: v.string(), entity_type: v.string(), entity_id: v.optional(v.string()), actor: v.string(), details: json, created_at: v.string() }).index("by_workspace", ["workspace_id"]),
  income_records: defineTable({ workspace_id: v.string(), client_name: v.string(), amount: v.number(), category: v.string(), payment_method: v.string(), status: v.string(), transaction_date: v.string(), created_at: v.string() }).index("by_workspace", ["workspace_id"]),
  ai_audits: defineTable({ workspace_id: v.string(), company_id: v.optional(v.string()), lead_id: v.optional(v.string()), audit_type: v.string(), overall_score: v.optional(v.number()), strengths: v.array(v.string()), weaknesses: v.array(v.string()), opportunities: v.array(v.string()), recommended_actions: v.array(v.string()), priority: v.optional(v.string()), source_data: json, created_at: v.string() }).index("by_workspace", ["workspace_id"]),
  prospect_outreach_events: defineTable({ workspace_id: v.string(), prospect_id: v.string(), opportunity_id: v.optional(v.string()), channel: v.string(), event_type: v.string(), content: v.optional(v.string()), external_id: v.optional(v.string()), metadata: json, occurred_at: v.string(), created_at: v.string() }).index("by_workspace", ["workspace_id"]).index("by_prospect", ["prospect_id"]),
  meta_connections: defineTable({ workspace_id: v.string(), provider: v.string(), page_id: v.optional(v.string()), page_name: v.optional(v.string()), status: v.string(), metadata: json, created_at: v.string(), updated_at: v.string() }).index("by_workspace", ["workspace_id"]),
});
