import { useEffect, useState } from 'react'
import { MessageCircle, Send } from 'lucide-react'
import { supabase, supabaseConfigured } from '../lib/supabase'
import type { Conversation, Message } from '../types/database'

export function ConversationsPage() {
  const [conversations, setConversations] = useState<Conversation[]>([])
  const [selected, setSelected] = useState<Conversation | null>(null)
  const [messages, setMessages] = useState<Message[]>([])
  const [draft, setDraft] = useState('')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  useEffect(() => { void (async () => { const { data, error: loadError } = await supabase.from('conversations').select('*, leads(contact_name, phone, status)').order('last_message_at', { ascending: false }); if (loadError) setError(loadError.message); const rows = (data as Conversation[]) ?? []; setConversations(rows); setSelected(rows[0] ?? null); setLoading(false) })() }, [])
  useEffect(() => { if (!selected) return; void (async () => { const { data } = await supabase.from('messages').select('*').eq('conversation_id', selected.id).order('created_at'); setMessages((data as Message[]) ?? []) })() }, [selected])
  const send = async () => { if (!draft.trim() || !selected) return; const { data } = await supabase.from('messages').insert({ conversation_id: selected.id, direction: 'outbound', sender_name: 'ZA Team', body: draft.trim(), ai_generated: false }).select().maybeSingle(); if (data) setMessages((current) => [...current, data as Message]); if (supabaseConfigured) await supabase.from('audit_logs').insert({ action: 'message.sent', entity_type: 'message', entity_id: data?.id ?? null, actor: 'dashboard', details: { conversation_id: selected.id } }); setDraft('') }
  return <div className="animate-fade-in space-y-4">
    {error && <div className="rounded-xl border border-error-200 bg-error-50 px-4 py-3 text-sm text-error-700">{error}<button className="ml-2 text-error-500 hover:text-error-700" onClick={() => setError('')}>Dismiss</button></div>}
    <div className="card flex min-h-[620px] overflow-hidden"><div className="w-full border-r border-neutral-200 md:w-80"><div className="border-b border-neutral-200 p-4"><h2 className="text-lg">Inbox</h2><p className="mt-1 text-xs text-neutral-500">{conversations.length} conversations</p></div><div className="divide-y divide-neutral-100">{loading ? <p className="p-5 text-sm text-neutral-400">Loading...</p> : conversations.map((conversation) => <button key={conversation.id} onClick={() => setSelected(conversation)} className={`w-full p-4 text-left transition-colors hover:bg-neutral-50 ${selected?.id === conversation.id ? 'bg-primary-50' : ''}`}><div className="flex items-center justify-between"><span className="font-semibold text-neutral-800">{conversation.leads?.contact_name ?? 'Unknown lead'}</span><span className="text-[10px] capitalize text-neutral-400">{conversation.channel}</span></div><p className="mt-1 text-xs text-neutral-500">{conversation.status}</p></button>)}{!loading && conversations.length === 0 && <div className="p-8 text-center text-sm text-neutral-400">No conversations yet.</div>}</div></div><div className="hidden flex-1 flex-col md:flex">{selected ? <><div className="border-b border-neutral-200 p-5"><h2 className="font-display text-lg">{selected.leads?.contact_name}</h2><p className="mt-1 text-xs text-neutral-500">{selected.channel} · {selected.leads?.phone ?? 'No phone number'}</p></div><div className="flex-1 space-y-3 overflow-y-auto bg-neutral-50/50 p-6">{messages.map((message) => <div key={message.id} className={`flex ${message.direction === 'outbound' ? 'justify-end' : 'justify-start'}`}><div className={`max-w-md rounded-2xl px-4 py-3 text-sm ${message.direction === 'outbound' ? 'bg-primary-600 text-white' : 'bg-white text-neutral-700 shadow-sm'}`}><p>{message.body}</p><p className={`mt-1 text-[10px] ${message.direction === 'outbound' ? 'text-primary-200' : 'text-neutral-400'}`}>{message.sender_name} · {new Date(message.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</p></div></div>)}{messages.length === 0 && <div className="m-auto text-center text-sm text-neutral-400"><MessageCircle className="mx-auto mb-2" size={24}/>No messages in this conversation.</div>}</div><div className="border-t border-neutral-200 p-4"><div className="flex gap-2"><input className="input" placeholder="Write a reply..." value={draft} onChange={(e) => setDraft(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter') void send() }}/><button className="btn-primary px-3" onClick={() => void send()}><Send size={16}/></button></div></div></> : <div className="flex flex-1 items-center justify-center text-sm text-neutral-400">Select a conversation to view messages.</div>}</div></div>
  </div>
}
