import { useEffect, useState, type FormEvent } from 'react'
import { CircleDollarSign, Plus, TrendingUp } from 'lucide-react'
import { supabase, supabaseConfigured } from '../lib/supabase'
import type { IncomeRecord } from '../types/database'
import { Modal } from '../components/Modal'

const emptyForm = { amount: '', type: 'project', status: 'pending', description: '' }

export function IncomePage() {
  const [records, setRecords] = useState<IncomeRecord[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [showModal, setShowModal] = useState(false)
  const [form, setForm] = useState(emptyForm)
  const [saving, setSaving] = useState(false)

  const load = async () => {
    setLoading(true); setError('')
    const { data, error: loadError } = await supabase.from('income_records').select('*, companies(name)').order('recorded_at', { ascending: false })
    if (loadError) setError(loadError.message)
    setRecords((data as IncomeRecord[]) ?? [])
    setLoading(false)
  }
  useEffect(() => { void load() }, [])

  const createRecord = async (e: FormEvent) => {
    e.preventDefault(); setSaving(true); setError('')
    const payload = { ...form, amount: Number(form.amount) || 0 }
    const { data, error: saveError } = await supabase.from('income_records').insert(payload).select().maybeSingle()
    if (saveError) { setError(saveError.message); setSaving(false); return }
    if (supabaseConfigured) await supabase.from('audit_logs').insert({ action: 'income_created', entity_type: 'income_record', actor: 'dashboard', details: { id: (data as IncomeRecord | null)?.id ?? 'unknown', amount: payload.amount } })
    setForm(emptyForm); setShowModal(false); await load(); setSaving(false)
  }

  const paid = records.filter((r) => r.status === 'paid').reduce((sum, r) => sum + Number(r.amount), 0)
  const pending = records.filter((r) => r.status === 'pending').reduce((sum, r) => sum + Number(r.amount), 0)

  return <div className="animate-fade-in space-y-6">
    <div className="flex items-end justify-between"><p className="text-sm text-neutral-500">Track revenue generated by your growth operations.</p><button className="btn-primary" onClick={() => setShowModal(true)}><Plus size={17}/> Add record</button></div>
    {error && <div className="rounded-xl border border-error-200 bg-error-50 px-4 py-3 text-sm text-error-700">{error}<button className="ml-2 text-error-500 hover:text-error-700" onClick={() => setError('')}>Dismiss</button></div>}
    <div className="grid gap-4 sm:grid-cols-2"><div className="card p-5"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-accent-50 text-accent-600"><CircleDollarSign size={19}/></div><div><div className="text-xs text-neutral-400">Paid revenue</div><div className="text-2xl font-display font-bold">${paid.toLocaleString()}</div></div></div></div><div className="card p-5"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-warning-50 text-warning-600"><TrendingUp size={19}/></div><div><div className="text-xs text-neutral-400">Pending</div><div className="text-2xl font-display font-bold">${pending.toLocaleString()}</div></div></div></div></div>
    <div className="card overflow-hidden"><div className="border-b border-neutral-200 p-5"><h2 className="text-lg">Income records</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-neutral-50 text-xs uppercase tracking-wider text-neutral-500"><tr><th className="px-5 py-3">Amount</th><th className="px-5 py-3">Type</th><th className="px-5 py-3">Status</th><th className="px-5 py-3">Description</th><th className="px-5 py-3">Recorded</th></tr></thead><tbody className="divide-y divide-neutral-100">{loading ? <tr><td colSpan={5} className="p-8 text-center text-neutral-400">Loading...</td></tr> : records.map((record) => <tr key={record.id}><td className="px-5 py-4 font-semibold">${Number(record.amount).toLocaleString()}</td><td className="px-5 py-4 capitalize">{record.type}</td><td className="px-5 py-4 capitalize">{record.status}</td><td className="px-5 py-4 text-neutral-600">{record.description || '—'}</td><td className="px-5 py-4 text-xs text-neutral-500">{new Date(record.recorded_at).toLocaleDateString()}</td></tr>)}{!loading && records.length===0 && <tr><td colSpan={5} className="p-8 text-center text-neutral-400">No income records yet.</td></tr>}</tbody></table></div></div>
    {showModal && <Modal title="Add income record" onClose={() => setShowModal(false)}><form onSubmit={createRecord} className="space-y-4"><input className="input" type="number" min="0" required placeholder="Amount" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })}/><select className="input" value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}><option value="project">Project</option><option value="retainer">Retainer</option><option value="commission">Commission</option><option value="refund">Refund</option></select><select className="input" value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option value="pending">Pending</option><option value="paid">Paid</option><option value="overdue">Overdue</option><option value="cancelled">Cancelled</option></select><input className="input" placeholder="Description" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })}/><div className="flex justify-end gap-3"><button type="button" className="btn-secondary" onClick={() => setShowModal(false)}>Cancel</button><button className="btn-primary" disabled={saving}>{saving ? 'Saving...' : 'Save record'}</button></div></form></Modal>}
  </div>
}
