/*
# Create ZE AI Operations core schema

1. New Tables
- `companies`: roofing/solar clients managed by ZE, with name, industry, status, and contact data.
- `social_pages`: Facebook and social pages connected to each company.
- `leads`: prospects captured from ads or messaging, including lead score, status, source, and contact fields.
- `campaigns`: marketing campaigns linked to companies and pages with budget and lifecycle status.
- `conversations`: customer conversations associated with leads and pages.
- `messages`: individual inbound/outbound conversation messages.
- `audit_logs`: immutable operational history for important actions.
- `income_records`: revenue and payment records linked to companies and leads.

2. Relationships and indexes
- Child records reference their parent company, page, lead, campaign, or conversation with foreign keys.
- Indexes support common dashboard filters for statuses, timestamps, and ownership relationships.

3. Security
- Row Level Security is enabled on every table.
- This is a single-tenant operations workspace without sign-in, so anon and authenticated roles receive CRUD access through explicit policies.

4. Important notes
- Timestamps are generated by the database.
- Status values are constrained to the supported workflow values.
- No destructive changes are made.
*/

CREATE TABLE IF NOT EXISTS public.companies (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  industry text NOT NULL DEFAULT 'Roofing',
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','paused','archived')),
  contact_name text,
  contact_email text,
  contact_phone text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.social_pages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  name text NOT NULL,
  platform text NOT NULL DEFAULT 'Facebook' CHECK (platform IN ('Facebook','Instagram','Google','Website','Other')),
  handle text,
  status text NOT NULL DEFAULT 'connected' CHECK (status IN ('connected','disconnected','attention')),
  followers integer NOT NULL DEFAULT 0 CHECK (followers >= 0),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.leads (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid REFERENCES public.companies(id) ON DELETE SET NULL,
  page_id uuid REFERENCES public.social_pages(id) ON DELETE SET NULL,
  full_name text NOT NULL,
  email text,
  phone text,
  property_address text,
  source text NOT NULL DEFAULT 'Facebook',
  status text NOT NULL DEFAULT 'new' CHECK (status IN ('new','contacted','qualified','appointment','won','lost')),
  score integer NOT NULL DEFAULT 0 CHECK (score BETWEEN 0 AND 100),
  project_type text NOT NULL DEFAULT 'Roofing',
  estimated_value numeric(12,2) NOT NULL DEFAULT 0 CHECK (estimated_value >= 0),
  last_contacted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.campaigns (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid REFERENCES public.companies(id) ON DELETE SET NULL,
  page_id uuid REFERENCES public.social_pages(id) ON DELETE SET NULL,
  name text NOT NULL,
  objective text NOT NULL DEFAULT 'Lead generation',
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','active','paused','completed')),
  budget numeric(12,2) NOT NULL DEFAULT 0 CHECK (budget >= 0),
  leads_count integer NOT NULL DEFAULT 0 CHECK (leads_count >= 0),
  spend numeric(12,2) NOT NULL DEFAULT 0 CHECK (spend >= 0),
  starts_at date,
  ends_at date,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.conversations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id uuid NOT NULL REFERENCES public.leads(id) ON DELETE CASCADE,
  page_id uuid REFERENCES public.social_pages(id) ON DELETE SET NULL,
  channel text NOT NULL DEFAULT 'Messenger' CHECK (channel IN ('Messenger','SMS','Email','WhatsApp','Phone')),
  status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','waiting','closed')),
  last_message_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
  direction text NOT NULL CHECK (direction IN ('inbound','outbound')),
  sender_name text NOT NULL,
  body text NOT NULL,
  ai_generated boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid,
  actor text NOT NULL DEFAULT 'system',
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.income_records (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid REFERENCES public.companies(id) ON DELETE SET NULL,
  lead_id uuid REFERENCES public.leads(id) ON DELETE SET NULL,
  amount numeric(12,2) NOT NULL CHECK (amount >= 0),
  type text NOT NULL DEFAULT 'project' CHECK (type IN ('project','retainer','commission','refund')),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','paid','overdue','cancelled')),
  description text,
  recorded_at date NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_social_pages_company ON public.social_pages(company_id);
CREATE INDEX IF NOT EXISTS idx_leads_status_created ON public.leads(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_leads_company ON public.leads(company_id);
CREATE INDEX IF NOT EXISTS idx_campaigns_status ON public.campaigns(status);
CREATE INDEX IF NOT EXISTS idx_conversations_last_message ON public.conversations(last_message_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_conversation_created ON public.messages(conversation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON public.audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_income_records_recorded ON public.income_records(recorded_at DESC);

ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.social_pages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.income_records ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Shared workspace companies select" ON public.companies;
CREATE POLICY "Shared workspace companies select" ON public.companies FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Shared workspace companies insert" ON public.companies;
CREATE POLICY "Shared workspace companies insert" ON public.companies FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "Shared workspace companies update" ON public.companies;
CREATE POLICY "Shared workspace companies update" ON public.companies FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Shared workspace companies delete" ON public.companies;
CREATE POLICY "Shared workspace companies delete" ON public.companies FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Shared workspace pages select" ON public.social_pages;
CREATE POLICY "Shared workspace pages select" ON public.social_pages FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Shared workspace pages insert" ON public.social_pages;
CREATE POLICY "Shared workspace pages insert" ON public.social_pages FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "Shared workspace pages update" ON public.social_pages;
CREATE POLICY "Shared workspace pages update" ON public.social_pages FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Shared workspace pages delete" ON public.social_pages;
CREATE POLICY "Shared workspace pages delete" ON public.social_pages FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Shared workspace leads select" ON public.leads;
CREATE POLICY "Shared workspace leads select" ON public.leads FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Shared workspace leads insert" ON public.leads;
CREATE POLICY "Shared workspace leads insert" ON public.leads FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "Shared workspace leads update" ON public.leads;
CREATE POLICY "Shared workspace leads update" ON public.leads FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Shared workspace leads delete" ON public.leads;
CREATE POLICY "Shared workspace leads delete" ON public.leads FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Shared workspace campaigns select" ON public.campaigns;
CREATE POLICY "Shared workspace campaigns select" ON public.campaigns FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Shared workspace campaigns insert" ON public.campaigns;
CREATE POLICY "Shared workspace campaigns insert" ON public.campaigns FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "Shared workspace campaigns update" ON public.campaigns;
CREATE POLICY "Shared workspace campaigns update" ON public.campaigns FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Shared workspace campaigns delete" ON public.campaigns;
CREATE POLICY "Shared workspace campaigns delete" ON public.campaigns FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Shared workspace conversations select" ON public.conversations;
CREATE POLICY "Shared workspace conversations select" ON public.conversations FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Shared workspace conversations insert" ON public.conversations;
CREATE POLICY "Shared workspace conversations insert" ON public.conversations FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "Shared workspace conversations update" ON public.conversations;
CREATE POLICY "Shared workspace conversations update" ON public.conversations FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Shared workspace conversations delete" ON public.conversations;
CREATE POLICY "Shared workspace conversations delete" ON public.conversations FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Shared workspace messages select" ON public.messages;
CREATE POLICY "Shared workspace messages select" ON public.messages FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Shared workspace messages insert" ON public.messages;
CREATE POLICY "Shared workspace messages insert" ON public.messages FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "Shared workspace messages update" ON public.messages;
CREATE POLICY "Shared workspace messages update" ON public.messages FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Shared workspace messages delete" ON public.messages;
CREATE POLICY "Shared workspace messages delete" ON public.messages FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Shared workspace audit select" ON public.audit_logs;
CREATE POLICY "Shared workspace audit select" ON public.audit_logs FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Shared workspace audit insert" ON public.audit_logs;
CREATE POLICY "Shared workspace audit insert" ON public.audit_logs FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "Shared workspace audit update" ON public.audit_logs;
CREATE POLICY "Shared workspace audit update" ON public.audit_logs FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Shared workspace audit delete" ON public.audit_logs;
CREATE POLICY "Shared workspace audit delete" ON public.audit_logs FOR DELETE TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "Shared workspace income select" ON public.income_records;
CREATE POLICY "Shared workspace income select" ON public.income_records FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Shared workspace income insert" ON public.income_records;
CREATE POLICY "Shared workspace income insert" ON public.income_records FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "Shared workspace income update" ON public.income_records;
CREATE POLICY "Shared workspace income update" ON public.income_records FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Shared workspace income delete" ON public.income_records;
CREATE POLICY "Shared workspace income delete" ON public.income_records FOR DELETE TO anon, authenticated USING (true);
